# Generated by Django 5.2.15 on 2026-07-06 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('price_from', models.CharField(max_length=50, verbose_name='Стартовая цена')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
