# Generated by Django 5.2.15 on 2026-07-07 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInclude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='main.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Элемент услуги',
                'verbose_name_plural': 'Элементы услуги',
            },
        ),
    ]
